### ISSUE TITLE
Arquivos de Distribuição

### ISSUE THREAD

**Issue by overlineink** [FranciiscoCampos170/todo-list-using-localstore-with-typescript#1]
Deveria remover os arquivos de distribuição [📁 **dist**] do projeto em desenvolvimento.
Recomendo vincular o bootstrap pelo **CDN** ou botar pra deps iniciando um arquivo **package.json**

**Comment by FranciiscoCampos170** [comment]
Valeu pela ajuda mano.

Na(o) sábado, 26/01/2019, 22:21, Jorge Dacosta <notifications@github.com>
escreveu:
